joint_limits:
  elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 3.14
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 2.62
    max_velocity: 3.33 
    min_position: -2.62
  shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 3.14
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 330.0
    max_position: 3.14159
    max_velocity: 2.28 
    min_position: -3.14159
  shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 3.14    
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 330.0
    max_position: 1.6
    max_velocity: 2.28
    min_position: -1.6
  wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 3.14
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: 3.14159
    max_velocity: 3.33 
    min_position: -3.14159
  wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 3.14
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: 3.14159
    max_velocity: 3.33 
    min_position: -3.14159
  wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 3.14
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: 3.5
    max_velocity: 3.33 
    min_position: -3.5